version: "3.9"
services:
  tf-serving:
    image: tf_serving:v1
    ports:
      - "8500:8500"
    
  gateway:
    image: gateway_tf_serving:v1
    environment:
      - TF_SERVING_HOST=tf-serving:8500
    ports:
      - "9000:9000"