apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pod
  template:
    metadata:
      labels:
        app: ping-pod
    spec:
      containers:
      - name: ping-container
        image: ping:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000