apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving
  template:
    metadata:
      labels:
        app: tf-serving
    spec:
      containers:
      - name: tf-serving
        image: 546106488772.dkr.ecr.eu-west-1.amazonaws.com/tf-gateway:tf_serving-v1
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 8500
